/**
 * Lumina Gallery - Curated Masterpiece Starter Collection
 * High-resolution award-winning photographs with complete camera telemetry and artistic narrative.
 */

export const INITIAL_PHOTOGRAPHS = [
    {
        id: 'lumina-masterpiece-01',
        title: 'Echoes of the Dolomites',
        category: 'landscape',
        url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=2560&q=85',
        thumbnailUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        rating: 5.0,
        badge: 'Grand Prize 2026',
        location: 'Tre Cime di Lavaredo, Italy',
        camera: 'Hasselblad X2D 100C',
        lens: 'XCD 38mm f/2.5 V',
        aperture: 'ƒ/8.0',
        shutterSpeed: '1/15s',
        iso: 'ISO 64',
        focalLength: '38mm',
        description: 'Captured during a fleeting three-minute break in dense alpine mist at sunrise. The medium format sensor resolved every needle of pine and glacial striation across the limestone faces.',
        favorite: true,
        views: 14280,
        aspectRatio: 'landscape',
        dateTaken: '2026-06-14',
        dateUploaded: 1718323200000
    },
    {
        id: 'lumina-masterpiece-02',
        title: 'Rain in Pontocho Alley',
        category: 'street',
        url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=2560&q=85',
        thumbnailUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
        rating: 4.9,
        badge: "Editor's Choice",
        location: 'Kyoto, Japan',
        camera: 'Leica M11 Monochrom',
        lens: 'Noctilux-M 50mm f/0.95 ASPH',
        aperture: 'ƒ/1.2',
        shutterSpeed: '1/250s',
        iso: 'ISO 1600',
        focalLength: '50mm',
        description: 'An umbrella silhouetted against glowing paper lanterns reflecting on wet flagstones. Handheld low-light capture emphasizing the interplay between deep shadows and warm tungsten luminescence.',
        favorite: true,
        views: 9840,
        aspectRatio: 'portrait',
        dateTaken: '2026-04-22',
        dateUploaded: 1713744000000
    },
    {
        id: 'lumina-masterpiece-03',
        title: 'Celestial Core over Atacama',
        category: 'astrophotography',
        url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=2560&q=85',
        thumbnailUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80',
        rating: 5.0,
        badge: 'Gold Award',
        location: 'Atacama Desert, Chile',
        camera: 'Sony α7R V (Astro Modified)',
        lens: 'Sony FE 14mm f/1.8 GM',
        aperture: 'ƒ/1.8',
        shutterSpeed: '20s',
        iso: 'ISO 3200',
        focalLength: '14mm',
        description: 'Tracked panoramic stack reveals the hydrogen-alpha emission nebulae along the galactic center. Zero light pollution at 4,800 meters altitude reveals airglow ripples on the horizon.',
        favorite: true,
        views: 18450,
        aspectRatio: 'landscape',
        dateTaken: '2026-05-19',
        dateUploaded: 1716076800000
    },
    {
        id: 'lumina-masterpiece-04',
        title: 'The Brutalist Monolith',
        category: 'architecture',
        url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=2560&q=85',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
        rating: 4.8,
        badge: "Curator's Selection",
        location: 'Valencia, Spain',
        camera: 'Canon EOS R5',
        lens: 'TS-E 17mm f/4L Tilt-Shift',
        aperture: 'ƒ/11',
        shutterSpeed: '1/60s',
        iso: 'ISO 100',
        focalLength: '17mm',
        description: 'Perspective-corrected architectural study of concrete curves meeting negative sky space. Filtered with a 6-stop ND to turn passing cirrus clouds into feather-soft directional streaks.',
        favorite: false,
        views: 6520,
        aspectRatio: 'landscape',
        dateTaken: '2026-03-08',
        dateUploaded: 1709856000000
    },
    {
        id: 'lumina-masterpiece-05',
        title: 'Gaze of the Snow Leopard',
        category: 'wildlife',
        url: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=2560&q=85',
        thumbnailUrl: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80',
        rating: 5.0,
        badge: 'Cover Story',
        location: 'Ladakh High Himalayas, India',
        camera: 'Nikon Z9',
        lens: 'NIKKOR Z 400mm f/2.8 TC VR S',
        aperture: 'ƒ/2.8',
        shutterSpeed: '1/2000s',
        iso: 'ISO 400',
        focalLength: '400mm',
        description: 'After fourteen days of sub-zero tracking, the ghost of the mountains paused on a jagged cliff edge. The amber eyes locked directly into the telephoto lens amidst a light flurry of powder snow.',
        favorite: true,
        views: 22100,
        aspectRatio: 'portrait',
        dateTaken: '2026-02-17',
        dateUploaded: 1708128000000
    },
    {
        id: 'lumina-masterpiece-06',
        title: 'Study in Ochre and Shadow',
        category: 'portrait',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=2560&q=85',
        thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
        rating: 4.9,
        badge: 'Exhibition Feature',
        location: 'Studio Marais, Paris',
        camera: 'Fujifilm GFX 100 II',
        lens: 'GF 110mm f/2 R LM WR',
        aperture: 'ƒ/2.0',
        shutterSpeed: '1/160s',
        iso: 'ISO 80',
        focalLength: '110mm',
        description: 'Natural northern window illumination sculpted with a single black velvet negative fill card. Masterful tonality rendering skin texture with microscopic detail and gentle rolloff.',
        favorite: false,
        views: 8930,
        aspectRatio: 'portrait',
        dateTaken: '2026-07-02',
        dateUploaded: 1719878400000
    },
    {
        id: 'lumina-masterpiece-07',
        title: 'Glacial Veins from the Stratosphere',
        category: 'fineart',
        url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2560&q=85',
        thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
        rating: 4.9,
        badge: 'Gold Award',
        location: 'Vatnajökull Ice Cap, Iceland',
        camera: 'Phase One IQ4 150MP',
        lens: 'Schneider Kreuznach 80mm LS f/2.8',
        aperture: 'ƒ/5.6',
        shutterSpeed: '1/1600s',
        iso: 'ISO 100',
        focalLength: '80mm',
        description: 'Aerial abstract looking straight down into braided volcanic meltwater rivers carving through obsidian black sand and turquoise glacial silt. Resembles neural pathways carved into earth.',
        favorite: true,
        views: 11200,
        aspectRatio: 'landscape',
        dateTaken: '2026-08-11',
        dateUploaded: 1723334400000
    },
    {
        id: 'lumina-masterpiece-08',
        title: 'Venetian Solitude at First Bell',
        category: 'street',
        url: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=2560&q=85',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=800&q=80',
        rating: 4.8,
        badge: "Curator's Selection",
        location: 'Grand Canal, Venice',
        camera: 'Leica Q3',
        lens: 'Summilux 28mm f/1.7 ASPH',
        aperture: 'ƒ/2.8',
        shutterSpeed: '1/80s',
        iso: 'ISO 400',
        focalLength: '28mm',
        description: 'A solitary gondolier slicing through sea-smoke as St. Mark’s campanile emerges in morning violet mist. Untouched by tourists, echoing timeless silence.',
        favorite: false,
        views: 7410,
        aspectRatio: 'landscape',
        dateTaken: '2026-05-04',
        dateUploaded: 1714780800000
    }
];
